#Define Output Structure (Schemas)
#Created a new file: schemas.py

#1. Reflection Class -Fields:
#missing → what is missing
#superfluous → unnecessary content

#2. Answer Class (AnswerQuestion)
#Fields:
#answer → 250-word response
#reflection → Reflection object
#search_queries → list (1–3 queries)

# Use Pydantic BaseModel

from typing import List

from pydantic import BaseModel, Field

# We want to address two important things in our critique 
#1. Missing information-means message which is important but LLM didnt generate
#2. Unnecessary content that doesnt add any value and generated by LLM
class Reflection(BaseModel):
    missing: str = Field(description="Critique of what is missing.")
    superfluous: str = Field(description="Critique of what is superfluous")


class AnswerQuestion(BaseModel):
    """Answer the question."""

    answer: str = Field(description="~250 word detailed answer to the question.")
    reflection: Reflection = Field(description="Your reflection on the initial answer.")
    search_queries: List[str] = Field(
        description="1-3 search queries for researching improvements to address the critique of your current answer."
    )

