#This node is going to take as an input the AI message, which is going to have the information of the wanted search queries.
# And it's going to run TAVILY to get us real time results and real time information from the web.

from dotenv import load_dotenv

load_dotenv()

from langchain_tavily import TavilySearch
from langchain_core.tools import StructuredTool #allows us to convert a Python function into a tool that can be used by llms.It provides to the LLM a structured schema for the function, which will help the LLM understand how to use this tool.
from langgraph.prebuilt import ToolNode #Detects tool calls,Executes the tool when called by llm, Returns result back to the graph

from cool_classes import AnswerQuestion, ReviseAnswer


# Create a Tavily tool instance
# max_results=5 → limits the number of search results returned per query
tavily_tool = TavilySearch(max_results=5)

# This function will be used as a TOOL inside LangGraph
def run_queries(search_queries: list[str], **kwargs):
    """
    Run the generated search queries using Tavily.

    Parameters:
    - search_queries (list[str]): List of search queries generated by the LLM
    - **kwargs: Extra arguments (ignored here but required for compatibility)

    What it does:
    - Converts each query into Tavily's expected format → {"query": "..."}
    - Calls tavily_tool.batch() to run multiple queries at once
    - Returns combined search results

    Example input:
        ["AI SOC startups funding", "Darktrace funding history"]

    Example transformed input:
        [{"query": "AI SOC startups funding"},
         {"query": "Darktrace funding history"}]
    """
    return tavily_tool.batch([{"query": query} for query in search_queries])

# Create a ToolNode (LangGraph prebuilt node)
# This node is responsible for EXECUTING tools when LLM calls them
execute_tools = ToolNode(
    [
        # Wrap the run_queries function as a StructuredTool
        # name=AnswerQuestion.__name__ → tool name becomes "AnswerQuestion"
        # This matches the schema/tool used by the Actor agent
        StructuredTool.from_function(
            run_queries,
            name=AnswerQuestion.__name__
        ),

        # Another tool using the SAME function but DIFFERENT name
        # name=ReviseAnswer.__name__ → tool name becomes "ReviseAnswer"
        # This matches the schema/tool used by the Reviser agent
        StructuredTool.from_function(
            run_queries,
            name=ReviseAnswer.__name__
        ),
    ]
)
